### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [2D-nz/petmatch#1]
Turma, por convenção, criamos os nomes de repositório no _github_ utilizando apenas letras minúsculas (_lower camel case_) e separamos as palavras utilizando _hyphen_ ao invés de _underline_.

Sugiro fazer o _rename_ do repositório seguindo a convenção de _nomeclatura_.

Outro ponto, o repositório deve conter o nome do projeto de acordo com o tema escolhido, não o nome da disciplina em questão.

**Comment by 2D-nz** [comment]
Projeto renomeado, em lowercamelcase e com o mesmo nome do projeto.

**Comment by professor-enoqueleal** [comment]
@2D-nz ,

Após concluir a _issue_, feche a mesma clicando no botão _close issue_
